---
<%
  http_port = ENV['KITCHEN_ICINGA2_HTTP_PORT'] || 8080
  https_port = ENV['KITCHEN_ICINGA2_HTTPS_PORT'] || 8443
  db_host = ENV['KITCHEN_DB_HOST'] || '127.0.0.1'
  db_port = ENV['KITCHEN_DB_PORT'] || '3306'
%>
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

verifier:
  name: inspec

provisioner:
  name: dokken
  log_file: "/tmp/chef-client.log"
  environment_path: test/environments
  data_bags_path: test/databags
  nodes_path: test/nodes
  attributes:
    apt:
      confd:
        install_recommends: false
    icinga2:
      ignore_version: false
    icingaweb2:
      ido:
        install_mysql_client: true

platforms:
  - name: ubuntu-14
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg
    attributes:
      icinga2-test-mysql-instance:
        service_manager: sysvinit

  - name: ubuntu-16
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: debian-8
    driver:
      image: debian:8.9
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: centos-6
    driver:
      image: centos:6.9
      pid_one_command: /sbin/init
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which curl
    attributes:
      icinga2-test-mysql-instance:
        service_manager: sysvinit

  - name: centos-7
    driver:
      image: centos:7
      pid_one_command: /usr/lib/systemd/systemd
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts systemd-sysv which lsof curl

  - name: fedora-26
    driver:
      image: fedora:26
      pid_one_command: /usr/lib/systemd/systemd
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts systemd-sysv which lsof curl

  - name: amazon
    driver:
      image: amazonlinux:2017.03
      pid_one_command: /sbin/init
      platform: amazon
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which

suites:
  - name: chef12server
    driver:
      chef_version: 12.21.4
    verifier:
      inspec_tests:
        - test/smoke/server
    run_list:
      - recipe[icinga2::default]
      - recipe[icinga2-test::default]
    attributes:
      icinga2:
        # temp fix
        disable_conf_d: false

  - name: chef13server
    driver:
      chef_version: 13.3.42
    verifier:
      inspec_tests:
        - test/smoke/server
    run_list:
      - recipe[icinga2::default]
      - recipe[icinga2-test::default]
    attributes:
      icinga2:
        # temp fix
        disable_conf_d: false

  - name: chef12web2
    driver:
      chef_version: 12.21.4
    verifier:
      inspec_tests:
        - test/smoke/web2
    run_list:
      - recipe[icinga2-test-mysql-instance::default]
      - recipe[icinga2::default]
      - recipe[icinga2-test::default]
      - recipe[icingaweb2::default]
    attributes:
      icinga2:
        # temp fix
        disable_conf_d: false
        chef12web2-centos-6: true
      icingaweb2:
        install_method: package
        ido:
          install_mysql_client: false
          db_host: <%= db_host %>
          db_port: <%= db_port %>
          db_password: X2BM0WKnN
          load_schema: true

  - name: chef13web2
    driver:
      chef_version: 13.3.42
    verifier:
      inspec_tests:
        - test/smoke/web2
    run_list:
      - recipe[icinga2-test-mysql-instance::default]
      - recipe[icinga2::default]
      - recipe[icinga2-test::default]
      - recipe[icingaweb2::default]
    attributes:
      icinga2:
        # temp fix
        disable_conf_d: false
        chef12web2-centos-6: true
      icingaweb2:
        install_method: package
        ido:
          install_mysql_client: false
          db_host: <%= db_host %>
          db_port: <%= db_port %>
          db_password: X2BM0WKnN
          load_schema: true
