---
<%
  db_host = ENV['KITCHEN_DB_HOST'] || 'localhost'
  chef_omnibus_url = ENV['KITCHEN_CHEF_OMNIBUS_URL'] || nil
%>
driver:
  name: vagrant

provisioner:
  name: chef_zero
  <% if chef_omnibus_url %>
  chef_omnibus_url: '<%= chef_omnibus_url %>'
  <% end %>

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-8.5

suites:
  - name: server
    run_list:
      - recipe[icinga2::server]
      - recipe[icinga2-test::default]

  - name: client
    run_list:
      - recipe[icinga2::client]

  - name: web2-package
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
    run_list:
      - recipe[icinga2::server]
      - recipe[icinga2-test::default]
    attributes:
      icinga2:
        web2:
          enable: true
          install_method: package
        ido:
          install_mysql_client: true
          db_host: <%= db_host %>
          load_schema: true
  - name: web2-source
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
    run_list:
      - recipe[icinga2::server]
      - recipe[icinga2-test::default]
    attributes:
      icinga2:
        web2:
          enable: true
          install_method: source
        ido:
          install_mysql_client: true
          db_host: <%= db_host %>
          load_schema: true
  - name: classicui
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
    run_list:
      - recipe[icinga2::server]
      - recipe[icinga2-test::default]
    attributes:
      icinga2:
        classic_ui:
          enable: true
