---
<%
  http_port = ENV['KITCHEN_ICINGA2_HTTP_PORT'] || 8080
  https_port = ENV['KITCHEN_ICINGA2_HTTPS_PORT'] || 8443
  db_host = ENV['KITCHEN_DB_HOST'] || 'localhost'
  chef_omnibus_url = ENV['KITCHEN_CHEF_OMNIBUS_URL'] || nil
%>
driver:
  name: dokken
  privileged: true
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  <% if chef_omnibus_url %>
  chef_omnibus_url: '<%= chef_omnibus_url %>'
  <% end %>

platforms:
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release

- name: debian-8
  driver:
    image: debian:8
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release

- name: centos-6.8
  driver:
    image: centos:6.8
    platform: rhel
    intermediate_instructions:
      - RUN yum install -y net-tools initscripts which

- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd
    platform: rhel
    intermediate_instructions:
      - RUN yum install -y net-tools initscripts systemd-sysv which lsof
